language: objective-c
osx_image: xcode6.4
before_script:
    - bundle install
script:
    - xcodebuild -project SquareRegisterSDK.xcodeproj -scheme "SquareRegisterSDK" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build
    - xcodebuild -project SquareRegisterSDK.xcodeproj -scheme "SquareRegisterSDK Tests" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 test
    - pod lib lint --verbose --fail-fast
