language: objective-c
osx_image: xcode8
rvm: 2.2.2
before_script:
    - bundle install
    - bundle exec pod install
script:
    - xcodebuild -project "SquareRegisterSDK.xcodeproj" -scheme "SquareRegisterSDK" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 -destination "platform=iOS Simulator,name=iPad Air 2" ACTIVE_ARCH_ONLY=0 build
    - xcodebuild -workspace "SquareRegisterSDK Tests.xcworkspace" -scheme "SquareRegisterSDK Tests" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 -destination "platform=iOS Simulator,name=iPad Air 2" ACTIVE_ARCH_ONLY=0 test
    - bundle exec pod lib lint --verbose --fail-fast
